# Generated by Django 2.2.6 on 2020-01-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=100)),
                ('aemail', models.CharField(max_length=200)),
                ('apwd', models.CharField(max_length=100)),
                ('aage', models.IntegerField()),
                ('agender', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNR_No', models.CharField(max_length=10)),
                ('Train_No', models.CharField(max_length=50)),
                ('Seat_No', models.IntegerField()),
                ('Date', models.DateField()),
                ('time', models.TimeField()),
                ('Booked_user_email', models.CharField(max_length=200)),
                ('Passenger_id', models.IntegerField()),
                ('Quota', models.CharField(max_length=100)),
                ('Status', models.CharField(default='Booked', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('msg', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='passenger',
            fields=[
                ('Passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('Passenger_name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=1)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('Station_Code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Station_name', models.CharField(max_length=100)),
                ('No_of_Platforms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('Train_No', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Train_name', models.CharField(max_length=100)),
                ('Source', models.CharField(max_length=10)),
                ('Destination', models.CharField(max_length=10)),
                ('Departure_time', models.TimeField()),
                ('Arrival_time', models.TimeField()),
                ('Capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Train_No', models.CharField(max_length=50)),
                ('Station_id', models.CharField(max_length=50)),
                ('Day', models.CharField(max_length=10)),
                ('Arrival_time', models.TimeField()),
                ('Departure_time', models.TimeField()),
                ('Platform_no', models.IntegerField()),
                ('Distance', models.IntegerField()),
            ],
            options={
                'unique_together': {('Train_No', 'Day', 'Arrival_time')},
            },
        ),
    ]
