# Generated by Django 2.2.6 on 2019-10-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='agender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
