# Generated by Django 2.2.6 on 2019-10-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicket', '0002_account_agender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='agender',
            field=models.CharField(max_length=1),
        ),
    ]
