# Generated by Django 2.2.6 on 2019-10-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicket', '0003_auto_20191002_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='Coach_No',
        ),
        migrations.AlterField(
            model_name='journey',
            name='PNR_No',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='Passenger_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
