# Generated by Django 2.2.6 on 2019-10-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicket', '0007_auto_20191025_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='Status',
            field=models.CharField(default='Booked', max_length=15),
        ),
    ]
