# Generated by Django 2.2.6 on 2019-11-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicket', '0010_auto_20191107_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seats',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='Booked_user',
        ),
        migrations.AddField(
            model_name='journey',
            name='Booked_user_email',
            field=models.CharField(default='user@gmail.com', max_length=200),
        ),
    ]
