# Generated by Django 2.2.6 on 2019-11-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTicket', '0011_auto_20191127_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='Booked_user_email',
            field=models.CharField(max_length=200),
        ),
    ]
